local L = AceLibrary("AceLocale-2.2"):new("BigTrouble")
L:RegisterTranslations("enUS", function()
return {
	["Aimed Shot"] = true,
	["Auto Shot"] = true,
	["UNIT_SPELLCAST_FAILED"] = "Failed",
	["UNIT_SPELLCAST_INTERRUPTED"] = "Interrupted",

	["lock"] = true,
	["Lock/Unlock the casting bar."] = true,
	["Unlocked"] = true,
	["Locked"] = true,
    ["autoshot"] = true,
	["Toggle Auto Shot casting bar."] = true,
	["On"] = true,
	["Off"] = true,
    ["aimedshot"] = true,
	["Toggle Aimed Shot casting bar."] = true,
	["texture"] = true,
	["Set the texture."] = true,
	["border"] = true,
	["Toggle the border."] = true,
	["width"] = true, 
	["Set the width of the casting bar."] = true,
	["height"] = true, 
	["Set the height of the casting bar."] = true,
	["font"] = true,
	["Set the font size of different elements."] = true,
	["spell"] = true, 
	["Set the font size of the spellname."] = true,
	["time"] = true, 
	["Set the font size of the spell time."] = true,
	["delay"] = true, 
	["Set the font size on the delay time."] = true,
	["Son of a bitch must pay!"] = true,
}
end)