local L = AceLibrary("AceLocale-2.2"):new("LittleTrouble")
L:RegisterTranslations("enUS", function()
return {
	["Aimed Shot"] = true,
	["Auto Shot"] = true,
	["colors"] = true,
	["Set the bar colors."] = true,
	["autoshot"] = true,
	["Sets the color of the auto shot bar."] = true,
	["lock"] = true,
	["Lock/Unlock the casting bar."] = true,
	["Unlocked"] = true,
	["Locked"] = true,
	["On"] = true,
	["Off"] = true,
	["texture"] = true,
	["Set the texture."] = true,
	["border"] = true,
	["Set the border for the bar."] = true,
	["width"] = true,
	["Set the width of the casting bar."] = true,
	["height"] = true,
	["Set the height of the casting bar."] = true,
	["font"] = true,
	["Set the font size of different elements."] = true,
	["spell"] = true,
	["Set the font size of the spellname."] = true,
	["time"] = true,
	["Set the font size of the spell time."] = true,
	["delay"] = true,
	["Set the font size on the delay time."] = true,
	["Son of a bitch must pay!"] = true,
}
end)