local L = AceLibrary("AceLocale-2.2"):new("BigTrouble")
L:RegisterTranslations("zhCN", function()
return {
	["Aimed Shot"] = "瞄准射击",
	["Auto Shot"] = "自动射击",
	["UNIT_SPELLCAST_FAILED"] = "失败",
	["UNIT_SPELLCAST_INTERRUPTED"] = "被打断",

	["lock"] = "lock",
	["Lock/Unlock the casting bar."] = "Lock/Unlock the casting bar.",
	["Unlocked"] = "Unlocked",
	["Locked"] = "Locked",
    ["autoshot"] = "autoshot",
	["Toggle Auto Shot casting bar."] = "Toggle Auto Shot casting bar.",
	["On"] = "On",
	["Off"] = "Off",
    ["aimedshot"] = "aimedshot",
	["Toggle Aimed Shot casting bar."] = "Toggle Aimed Shot casting bar.",
	["texture"] = "texture",
	["Set the texture."] = "Set the texture.",
	["border"] = "border",
	["Toggle the border."] = "Toggle the border.",
	["width"] = "width", 
	["Set the width of the casting bar."] = "Set the width of the casting bar.",
	["height"] = "height", 
	["Set the height of the casting bar."] = "Set the height of the casting bar.",
	["font"] = "font",
	["Set the font size of different elements."] = "Set the font size of different elements.",
	["spell"] = "spell", 
	["Set the font size of the spellname."] = "Set the font size of the spellname.",
	["time"] = "time", 
	["Set the font size of the spell time."] = "Set the font size of the spell time.",
	["delay"] = "delay", 
	["Set the font size on the delay time."] = "Set the font size on the delay time.",
	["Son of a bitch must pay!"] = "Son of a bitch must pay!",
}
end)