local L = AceLibrary("AceLocale-2.2"):new("LittleTrouble")
L:RegisterTranslations("koKR", function()
return {
	["Aimed Shot"] = "조준 사격",
	["Auto Shot"] = "자동 사격",
	["colors"] = "colors",
	["Set the bar colors."] = "Set the bar colors.",
	["autoshot"] = "autoshot",
	["Sets the color of the auto shot bar."] = "Sets the color of the auto shot bar.",
	["lock"] = "lock",
	["Lock/Unlock the casting bar."] = "Lock/Unlock the casting bar.",
	["Unlocked"] = "Unlocked",
	["Locked"] = "Locked",
	["On"] = "On",
	["Off"] = "Off",
	["texture"] = "texture",
	["Set the texture."] = "Set the texture.",
	["border"] = "border",
	["Toggle the border."] = "Toggle the border.",
	["width"] = "width", 
	["Set the width of the casting bar."] = "Set the width of the casting bar.",
	["height"] = "height", 
	["Set the height of the casting bar."] = "Set the height of the casting bar.",
	["font"] = "font",
	["Set the font size of different elements."] = "Set the font size of different elements.",
	["spell"] = "spell",
	["Set the font size of the spellname."] = "Set the font size of the spellname.",
	["time"] = "time",
	["Set the font size of the spell time."] = "Set the font size of the spell time.",
	["delay"] = "delay",
	["Set the font size on the delay time."] = "Set the font size on the delay time.",
	["Son of a bitch must pay!"] = "Son of a bitch must pay!",
}
end)